### PR TITLE
Update README.md to use an Gnome extensions badge

### PR DESCRIPTION
**Pull request by pablotrianda**
Hi! This PR is to add the link to: [Gnome extension page](https://extensions.gnome.org/extension/3968/improved-workspace-indicator/) on install instructions.

Cheers!

### CODE REVIEW

**Comment by tfuxu** [comment]
@pablotrianda 
I would suggest to you to just use an Gnome extensions badge: https://github.com/andyholmes/gnome-shell-extensions-badge

**Comment by tfuxu** [comment]
Here's how GSConnect has this set in README: https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/2039513393da9279206c874abdda16ced427532e/README.md?plain=1#L9

**Comment by pablotrianda** [comment]
Nice! I will change for a new badget

**Review by MichaelAquilina — APPROVED** [review]
Amazing :) thanks for the contribution @pablotrianda and the suggestion @tfuxu !

**Pull request merged**
